/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_DuAn;

import FileEX.XuatFileXl;

/**
 *
 * @author Administrator
 */
public class GiaoDienQLCT extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
    public GiaoDienQLCT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCongnhan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnNguyenlieu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnChiphikhac = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnXuatfile = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi tiêu dự án");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCongnhan.setBackground(new java.awt.Color(255, 153, 153));
        btnCongnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Occupations-Firefighter-Female-Light-icon.png"))); // NOI18N
        btnCongnhan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCongnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongnhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnCongnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 101, 120, 110));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Thuê nhân công");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnNguyenlieu.setBackground(new java.awt.Color(255, 153, 153));
        btnNguyenlieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nguyenlieu.png"))); // NOI18N
        btnNguyenlieu.setToolTipText("");
        btnNguyenlieu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNguyenlieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguyenlieuActionPerformed(evt);
            }
        });
        getContentPane().add(btnNguyenlieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 105, 132, 110));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Mua nguyên vật liệu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 0));
        jLabel6.setText("Thống kê chi tiêu dự án");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        btnChiphikhac.setBackground(new java.awt.Color(255, 153, 153));
        btnChiphikhac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phuphithem.png"))); // NOI18N
        btnChiphikhac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnChiphikhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiphikhacActionPerformed(evt);
            }
        });
        getContentPane().add(btnChiphikhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 105, 129, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Chi phí khác");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        btnXuatfile.setBackground(new java.awt.Color(255, 153, 153));
        btnXuatfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/document-excel-icon.png"))); // NOI18N
        btnXuatfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });
        getContentPane().add(btnXuatfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 105, 129, 110));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Xuất file");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        btnThoat.setBackground(new java.awt.Color(255, 255, 0));
        btnThoat.setForeground(new java.awt.Color(0, 0, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lovepik-background-of-scientific-and-technological-image_400083927.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNguyenlieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguyenlieuActionPerformed
        // TODO add your handling code here:
        NguyenVatLieu nvl = new NguyenVatLieu();
        nvl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNguyenlieuActionPerformed

    private void btnCongnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongnhanActionPerformed
        // TODO add your handling code here:
        ThueNhanCong nc = new ThueNhanCong();
        nc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCongnhanActionPerformed

    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        // TODO add your handling code here:
        XuatFileXl xp = new XuatFileXl();
        xp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnXuatfileActionPerformed

    private void btnChiphikhacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiphikhacActionPerformed
        // TODO add your handling code here:
        ChiPhiKhac cpk = new ChiPhiKhac();
        cpk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChiphikhacActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        BangPhanCong frm = new BangPhanCong();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQLCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQLCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQLCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQLCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienQLCT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiphikhac;
    private javax.swing.JButton btnCongnhan;
    private javax.swing.JButton btnNguyenlieu;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXuatfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
