/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_DuAn;

import DataBase.DBAccess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static QL_DuAn.BangPhanCong.MaDA;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import FileEX.TTxuatNVL;

/**
 *
 * @author Administrator
 */
public class NguyenVatLieu extends javax.swing.JFrame {
    public ResultSet rs = null;

    /**
     * Creates new form NguyenLieu
     */
    public NguyenVatLieu() {
        initComponents();
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabNguyenlieu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtTenNVL = new javax.swing.JTextField();
        cbbDonvitinh = new javax.swing.JComboBox<>();
        txtDongia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNhacungcap = new javax.swing.JTextPane();
        spinSoluong = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống kê nguyên vật liệu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabNguyenlieu.setBackground(new java.awt.Color(255, 255, 153));
        tabNguyenlieu.setForeground(new java.awt.Color(0, 0, 255));
        tabNguyenlieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nguyên liệu", "Tên nguyên liệu", "Nơi cung cấp", "Số lượng", "Đơn vị tính", "Đơn giá", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabNguyenlieu.getTableHeader().setReorderingAllowed(false);
        tabNguyenlieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabNguyenlieuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabNguyenlieu);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 201, 1140, 182));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Quản lí nguyên vật liệu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Tên nguyên liệu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 151, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Mã nguyên liệu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 104, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Đơn giá");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 108, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Nơi cung cấp");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 151, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Số lượng");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 104, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Đơn vị tính");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 151, -1, -1));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add_16x16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 411, 90, 30));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit_16x16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 80, 30));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh_16x16.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 99, 30));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 80, 30));

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 410, 80, 30));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 101, 123, -1));
        getContentPane().add(txtTenNVL, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 148, 170, -1));

        cbbDonvitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tấn", "m^3", "kg", "Bao", "Viên", "Cây" }));
        getContentPane().add(cbbDonvitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 148, 73, -1));
        getContentPane().add(txtDongia, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 105, 143, -1));

        jScrollPane1.setViewportView(txtNhacungcap);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 147, 190, 40));

        spinSoluong.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        getContentPane().add(spinSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 101, 70, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nguyenvatlieu.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void LoadData () 
    {
        DBAccess acc = new DBAccess();
        try { 
            rs = acc.Query("select * from QLNguyenVatLieu where IDDA = '"+MaDA+"'");
            String [] arr = {"Mã nguyên liệu","Tên nguyên liệu","Nơi cung cấp","Số lượng","Đơn vị tính","Đơn giá","Tổng tiền"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDNVL"));
                vec.add(rs.getString("TenNVL"));
                vec.add(rs.getString("NoiCungCap"));
                vec.add(rs.getInt("SoLuongSP"));
                vec.add(rs.getString("DonViTinh"));
                vec.add(rs.getInt("DonGia"));
                vec.add(rs.getInt("TongTien"));
                
                model.addRow(vec);
                
                TTxuatNVL.IDNVL=rs.getString("IDNVL");
                TTxuatNVL.TenNVL=rs.getString("TenNVL");
                TTxuatNVL.NoiCungCap=rs.getString("NoiCungCap");
                TTxuatNVL.SoLuong=rs.getInt("SoLuongSP");
                TTxuatNVL.Donvitinh=rs.getString("DonViTinh");
                TTxuatNVL.Dongia=rs.getInt("DonGia");
                TTxuatNVL.Tongtien=rs.getInt("TongTien");
            }
            tabNguyenlieu.setModel(model);
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(NguyenVatLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnSua.setEnabled(false);
    }
    private void tabNguyenlieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabNguyenlieuMouseClicked
        // TODO add your handling code here:
        int i = tabNguyenlieu.getSelectedRow();
        TableModel model = tabNguyenlieu.getModel();
        cbbDonvitinh.setSelectedItem(model.getValueAt(i, 4).toString());
        txtID.setText(model.getValueAt(i, 0).toString());
        txtTenNVL.setText(model.getValueAt(i, 1).toString());
        txtNhacungcap.setText(model.getValueAt(i, 2).toString());
        spinSoluong.setValue(model.getValueAt(i, 3).hashCode());
        txtDongia.setText(model.getValueAt(i, 5).toString());
        txtID.setEditable(false);
        btnSua.setEnabled(true);
    }//GEN-LAST:event_tabNguyenlieuMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        if(txtTenNVL.getText().equals("") || txtID.getText().equals("") || txtDongia.getText().equals("") || txtNhacungcap.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin !!");
        }else{
            if(spinSoluong.getValue().hashCode() <= 0 ){
                JOptionPane.showMessageDialog(this, "Số lượng sản phẩm phải lớn hơn 0 !!!");
                spinSoluong.setValue(1);
            }else{
                String IDNVL = txtID.getText();
                String TenNVL = txtTenNVL.getText();
                String Donvitinh = (String) cbbDonvitinh.getSelectedItem();
                String Noicungcap = (String) txtNhacungcap.getText();
                int SoLuong = (int) spinSoluong.getValue();
                int Dongia = Integer.parseInt(txtDongia.getText());
                int TongTien;
                TongTien = Dongia * SoLuong;
                System.out.println(TongTien);
                rs = acc.Query("select IDNVL from QLNguyenVatLieu where IDNVL = '"+IDNVL+"'");
                try {if(rs.next())
                    {
                        JOptionPane.showMessageDialog(this, "Mã vật liệu đã tồn tại !!!");
                    }else{
                        acc.Update("insert into QLNguyenVatLieu values('"+IDNVL+"',N'"+TenNVL+"',N'"+Noicungcap+"','"+SoLuong+"',N'"+Donvitinh+"','"+Dongia+"','"+TongTien+"','"+MaDA+"')");     
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NguyenVatLieu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } 
        LoadData();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        int remove = tabNguyenlieu.getSelectedRow();
        if(remove == -1){
            JOptionPane.showMessageDialog(null, "vui lòng chọn 1 dòng để sửa !!!");
        }else{
            if(txtTenNVL.getText().equals("") || txtDongia.getText().equals("") || txtNhacungcap.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin !!");
            }else{
                if(spinSoluong.getValue().hashCode() <= 0 ){
                    JOptionPane.showMessageDialog(this, "Số lượng sản phẩm phải lớn hơn 0 !!!");
                    spinSoluong.setValue(1);
                }else{
                    String IDNVL = txtID.getText();
                    String TenNVL = txtTenNVL.getText();
                    String Donvitinh = (String) cbbDonvitinh.getSelectedItem();
                    String Noicungcap = (String) txtNhacungcap.getText();
                    int SoLuong = (int) spinSoluong.getValue();
                    int Dongia = Integer.parseInt(txtDongia.getText());
                    int TongTien;
                    TongTien = Dongia * SoLuong;
                    acc.Update("update QLNguyenVatLieu set TenNVL = N'"+TenNVL+"',NoiCungCap = N'"+Noicungcap+"',SoLuongSP = '"+SoLuong+"',"
                            + "DonViTinh = '"+Donvitinh+"',DonGia = '"+Dongia+"',TongTien = '"+TongTien+"' where IDNVL = '"+IDNVL+"' and IDDA = '"+MaDA+"' )");
                }
            } 
            LoadData();
        }   
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        cbbDonvitinh.setSelectedIndex(0);
        txtTenNVL.setText("");
        txtID.setText("");
        txtDongia.setText("");
        spinSoluong.setValue(1);
        txtNhacungcap.setText("");
        txtID.setEditable(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        int remove = tabNguyenlieu.getSelectedRow();
        if(remove == -1){
            JOptionPane.showMessageDialog(null, "vui lòng chọn 1 dòng để xóa !!!");
        }else{
            String IDNVL = txtID.getText();
            acc.Update("DELETE from QLNguyenVatLieu where IDNVL = '"+IDNVL+"' and IDDA = '"+MaDA+"' ");
        }
        LoadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        GiaoDienQLCT frm = new GiaoDienQLCT();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguyenVatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguyenVatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguyenVatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguyenVatLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NguyenVatLieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbDonvitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinSoluong;
    private javax.swing.JTable tabNguyenlieu;
    private javax.swing.JTextField txtDongia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextPane txtNhacungcap;
    private javax.swing.JTextField txtTenNVL;
    // End of variables declaration//GEN-END:variables
}
