/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_DuAn;

import FileEX.TTxuatNC;
import DataBase.DBAccess;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static QL_DuAn.BangPhanCong.MaDA;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Administrator
 */
public class ThueNhanCong extends javax.swing.JFrame {
    public static ResultSet rs = null ;

    /**
     * Creates new form NhanCong
     */
    public ThueNhanCong() {
        initComponents();
        LoadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void LoadData () 
    {
        DBAccess acc = new DBAccess();
        try { 
            rs = acc.Query("select * from QLCongNhan,ChucVuCongNhan,ChiTietCongNhan where QLCongNhan.IDCVCN = ChucVuCongNhan.IDCVCN and ChiTietCongNhan.IDCN = QLCongNhan.IDCN and IDDA = '"+MaDA+"'");
            String [] arr = {"Mã công nhân","Họ tên","Giới tính","Số điện thoại","Chức vụ","Số ngày làm","Lương cơ bản","Thưởng","Tổng Lương"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDCN"));
                vec.add(rs.getString("HoTen"));
                vec.add(rs.getString("GioiTinh"));
                vec.add(rs.getString("SDT"));
                vec.add(rs.getString("ChucVu"));
                vec.add(rs.getInt("SoNgayLam"));
                vec.add(rs.getInt("LuongCoBan"));
                vec.add(rs.getInt("Thuong"));
                vec.add(rs.getInt("TongLuong"));
                
                model.addRow(vec);
                
                TTxuatNC.IDNC=rs.getString("IDCN");
                TTxuatNC.HoTen=rs.getString("HoTen");
                TTxuatNC.GioiTinh=rs.getString("GioiTinh");
                TTxuatNC.SDT=rs.getString("SDT");
                TTxuatNC.Chucvu=rs.getString("ChucVu");
                TTxuatNC.Songaylam=rs.getInt("SoNgayLam");
                TTxuatNC.Luongcoban=rs.getInt("LuongCoBan");
                TTxuatNC.thuong=rs.getInt("Thuong");
                TTxuatNC.tongluong=rs.getInt("TongLuong");
            }
            tabCongnhan.setModel(model);
            rs.close();
            txtLuongCB.setEditable(false);
        } catch (SQLException ex) {
            Logger.getLogger(ThueNhanCong.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtChucvu.setEditable(false);
    }
    public int luongCB(String chucvu)
    {
        DBAccess acc = new DBAccess();
        int lcb = 0;
        try { 
            rs = acc.Query("select LuongCoBan from ChucVuCongNhan where ChucVu = N'"+chucvu+"'");
            while(rs.next())
            {
                txtLuongCB.setText(rs.getString("LuongCoBan"));
                lcb = rs.getInt("LuongCoBan");
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(ThueNhanCong.class.getName()).log(Level.SEVERE, null, ex);
        } 
        return lcb;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabCongnhan = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbbDieukien = new javax.swing.JComboBox<>();
        txtLuongCB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        spinSongaylam = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        listID = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listHoten = new javax.swing.JList<>();
        txtChucvu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống kê thuê công nhân");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Quản lí thuê nhân công");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit_16x16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add_16x16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 430, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Mã công nhân");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Lương cơ bản");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Chức vụ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, 25));

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, -1));

        tabCongnhan.setBackground(new java.awt.Color(255, 255, 153));
        tabCongnhan.setForeground(new java.awt.Color(0, 0, 204));
        tabCongnhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã công nhân", "Họ tên", "Giới tính", "Số điện thoại", "Chức vụ", "Số ngày làm", "Lương cơ bản", "Thưởng", "Tổng lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabCongnhan.getTableHeader().setReorderingAllowed(false);
        tabCongnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCongnhanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabCongnhan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 219, 1109, 182));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 430, -1, -1));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh_16x16.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Điều kiện thưởng");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        cbbDieukien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không có", "Làm ít nhất 30 ngày", "Làm ít nhất 100 ngày", "Làm ít nhất 200 ngày", " ", " ", " ", " " }));
        getContentPane().add(cbbDieukien, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 150, -1));
        getContentPane().add(txtLuongCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Số ngày làm");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));
        getContentPane().add(spinSongaylam, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 59, -1));

        listID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listIDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listID);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 140, 50));

        jScrollPane4.setViewportView(listHoten);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 140, 30));
        getContentPane().add(txtChucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nhancong.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1147, 472));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private float Thuong()
    {
        DBAccess acc = new DBAccess(); 
        float thuong = 0;
        try { 
            String dieukien = (String) cbbDieukien.getSelectedItem();
            rs = acc.Query("select * from Thuong where DieuKien = N'"+dieukien+"'");
            while(rs.next())
            {
                thuong = rs.getFloat("MucThuong");
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(ThueNhanCong.class.getName()).log(Level.SEVERE, null, ex);
        }     
        return thuong;
    }
    public void XoaTrang()
    {
        ListModel m = (ListModel)listID.getModel();
        m.removeListDataListener((ListDataListener) txtID);
    }
    
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        cbbDieukien.setSelectedIndex(0);
        txtChucvu.setText("");
        txtID.setText("");
        txtLuongCB.setText("");
        spinSongaylam.setValue(1);
        txtID.setEditable(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        GiaoDienQLCT frm = new GiaoDienQLCT();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tabCongnhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCongnhanMouseClicked
        // TODO add your handling code here:
        int i = tabCongnhan.getSelectedRow();
        TableModel model = tabCongnhan.getModel();
        txtChucvu.setText(model.getValueAt(i, 4).toString());
        txtID.setText(model.getValueAt(i, 0).toString());
        txtLuongCB.setText(model.getValueAt(i, 6).toString());
        spinSongaylam.setValue(model.getValueAt(i, 5).hashCode());
        txtLuongCB.setEditable(false);
        txtID.setEditable(false);
        int snl = model.getValueAt(i, 5).hashCode();
        if(snl>=30 && snl<100){
            cbbDieukien.setSelectedIndex(1);
        }else{
            if(snl >= 100 && snl <200){
                cbbDieukien.setSelectedIndex(2);
            }else{
                if(snl >= 200){
                    cbbDieukien.setSelectedIndex(3);
                }else{
                    cbbDieukien.setSelectedIndex(0);
                }
            }
        }
    }//GEN-LAST:event_tabCongnhanMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        if(listID.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "vui lòng chọn 1 thông tin");
        }else{
            String IDCN = listID.getSelectedValue();
            int SoNgayLam = (int) spinSongaylam.getValue();
            String chucvu = txtChucvu.getText();
            int luongcb = luongCB(chucvu);
            int tong = luongcb * SoNgayLam;
            int Thuong = (int) (tong * Thuong());
            float TongLuong = (float) (tong + Thuong);
            rs = acc.Query("select IDCN from QLCongNhan where IDCN = '"+IDCN+"'");
            try {
                if(rs.next()){
                    acc.Update("insert into ChiTietCongNhan values ('"+MaDA+"','"+Thuong+"','"+SoNgayLam+"','"+TongLuong+"','"+IDCN+"')");    
                }else{
                    JOptionPane.showMessageDialog(this, "Mã công nhân không tồn tại !!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ThueNhanCong.class.getName()).log(Level.SEVERE, null, ex);
            }
            LoadData();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        String IDCN = txtID.getText();
        int songaylam = (int) spinSongaylam.getValue();
        String chucvu = txtChucvu.getText();
        int luongcb = luongCB(chucvu);
        float TongLuong = (float) (luongcb + luongcb * Thuong());
        acc.Update("update ChiTietCongNhan set MucThuong = '"+Thuong()+"',SoNgayLam = '"+songaylam+"',TongLuong = '"+TongLuong+"' where IDDA = '"+MaDA+"' and IDCN = '"+IDCN+"'");
        LoadData();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        int remove = tabCongnhan.getSelectedRow();
        if(remove == -1){
            JOptionPane.showMessageDialog(null, "vui lòng chọn 1 dòng để xóa !!!");
        }else{
            String IDCN = txtID.getText();
            acc.Update("DELETE from ChiTietCongNhan where IDCN = '"+IDCN+"' and IDDA = '"+MaDA+"' ");
        }
        LoadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        // TODO add your handling code here:
        //XoaTrangTABBLE();
        String IDCN = txtID.getText();
        DBAccess acc = new DBAccess();
         try{
            if(!txtID.getText().equals("")){
                listID.setEnabled(true);
                rs = acc.Query("select * from QLCongNhan,ChucVuCongNhan where IDCN like '%"+IDCN+"%' and QLCongNhan.IDCVCN = ChucVuCongNhan.IDCVCN ");
                DefaultListModel listModel = new DefaultListModel();
                while(rs.next())
                {
                    listID.setModel(listModel);
                    listModel.addElement(rs.getString("IDCN"));
                }
            }else{
                listHoten.setEnabled(false);
                listID.setEnabled(false);
            }
        }catch (SQLException ex) {
            Logger.getLogger(ThueNhanCong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIDKeyReleased

    private void listIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listIDMouseClicked
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        String IDCN = listID.getSelectedValue();
        rs = acc.Query("select HoTen,ChucVu from QLCongNhan,ChucVuCongNhan where IDCN = '"+IDCN+"' and QLCongNhan.IDCVCN = ChucVuCongNhan.IDCVCN");
        DefaultListModel listModel = new DefaultListModel();
        try {
            while(rs.next())
            { 
                listHoten.setModel(listModel);
                listModel.addElement(rs.getString("HoTen"));
                txtChucvu.setText(rs.getString("ChucVu"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThueNhanCong.class.getName()).log(Level.SEVERE, null, ex);
        }
        listHoten.setEnabled(false);
    }//GEN-LAST:event_listIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThueNhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThueNhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThueNhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThueNhanCong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ThueNhanCong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbDieukien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listHoten;
    private javax.swing.JList<String> listID;
    private javax.swing.JSpinner spinSongaylam;
    private javax.swing.JTable tabCongnhan;
    private javax.swing.JTextField txtChucvu;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLuongCB;
    // End of variables declaration//GEN-END:variables
}
