/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_DuAn;
import TaiKhoan.*;

/**
 *
 * @author Administrator
 */
public class TrangChuDangNhapNV extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuDangNhapNV
     */
    public TrangChuDangNhapNV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTaikhoan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnBangphancong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDangxuat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTaikhoan.setBackground(new java.awt.Color(255, 255, 153));
        btnTaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User-icon.png"))); // NOI18N
        btnTaikhoan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaikhoanActionPerformed(evt);
            }
        });
        getContentPane().add(btnTaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 116, 110));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Tài khoản");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        btnBangphancong.setBackground(new java.awt.Color(255, 255, 153));
        btnBangphancong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User-Files-icon.png"))); // NOI18N
        btnBangphancong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBangphancong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangphancongActionPerformed(evt);
            }
        });
        getContentPane().add(btnBangphancong, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 128, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Bảng phân công");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        btnDangxuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangxuat.setForeground(new java.awt.Color(255, 102, 102));
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Log Out_16x16.png"))); // NOI18N
        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trangchuqlda.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 387, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBangphancongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangphancongActionPerformed
        // TODO add your handling code here:
        BangPhanCong frm = new BangPhanCong();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBangphancongActionPerformed

    private void btnTaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaikhoanActionPerformed
        // TODO add your handling code here:
        Account ac = new Account();
        ac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTaikhoanActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:
        TaikhoanNV tk = new TaikhoanNV();
        tk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDangxuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuDangNhapNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuDangNhapNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuDangNhapNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuDangNhapNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TrangChuDangNhapNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBangphancong;
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnTaikhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
