/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;

import DataBase.DBAccess;
import java.awt.Color;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class QLDuAn extends javax.swing.JFrame {
    public static ResultSet rs = null ,rs1 = null;

    /**
     * Creates new form QL_DuAn
     */
    public QLDuAn() {
        initComponents();
        LoadData();
        long millis=System.currentTimeMillis();   
        Date date=new java.sql.Date(millis);   
        cldNgaykiHD.setDate(date);
        cldTimeDK.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabDuanCHT = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenDA = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtDatcoc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiadiem = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        cldTimeDK = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cldNgaykiHD = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtIDKH = new javax.swing.JTextField();
        txtTiendo = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí dự án");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("QUẢN LÍ DỰ ÁN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 13, -1, -1));

        tabDuanCHT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dự án", "Tên dự án", "Mã khách hàng", "Khách hàng", "Địa điểm", "Ngày kí hợp đồng", "Thời gian dự kiến hoàn thành", "Đặt cọc", "Tiến độ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabDuanCHT.getTableHeader().setReorderingAllowed(false);
        tabDuanCHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDuanCHTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabDuanCHT);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 1148, 182));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Mã dự án");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Tên dự án");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Đặt cọc");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        getContentPane().add(txtTenDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 139, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 139, -1));
        getContentPane().add(txtDatcoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 139, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        jLabel7.setText("Tiến độ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("Tên khách hàng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));
        getContentPane().add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 139, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("Địa điểm");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 77, -1, -1));

        jScrollPane1.setViewportView(txtDiadiem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 77, 203, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("Thời gian dự kiến");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, -1, -1));

        cldTimeDK.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(cldTimeDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, 170, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setText("Ngày kí hợp đồng");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        cldNgaykiHD.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(cldNgaykiHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 153));
        jLabel10.setText("Mã khách hàng");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        txtIDKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKHKeyReleased(evt);
            }
        });
        getContentPane().add(txtIDKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 77, 140, -1));
        getContentPane().add(txtTiendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 140, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add_16x16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit_16x16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh_16x16.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 430, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngtree-company-promotion-poster-background-material-picture-image_1118650.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 475));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void LoadData () 
    {
        DBAccess acc = new DBAccess();
        try
        {
                rs = acc.Query("select DuAn.IDDA,TenDA,DuAn.IDKH,HoTenKH,DiaDiem,NgayKiHopDong,ThoiGianDuKienHoanThanh,DatCoc,TienDoDA\n" +
                                "from DuAn,QLThongTinKH\n" +
                                "where QLThongTinKH.IDKH = DuAn.IDKH order by DuAn.IDDA");
            String [] arr = {"Mã dự án","Tên dự án","Mã khách hàng","Tên khách hàng","Địa điểm","Ngày kí hợp đồng","Thời gian dự kiến hoàn thành","Đặt cọc","Tiến độ"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDDA"));
                vec.add(rs.getString("TenDA"));
                vec.add(rs.getString("IDKH"));
                vec.add(rs.getString("HoTenKH"));
                vec.add(rs.getString("DiaDiem")); 
                vec.add(rs.getString("NgayKiHopDong"));
                vec.add(rs.getString("ThoiGianDuKienHoanThanh"));
                vec.add(rs.getInt("DatCoc"));
                vec.add(rs.getString("TienDoDA")); 

                model.addRow(vec);
            }
            tabDuanCHT.setModel(model);
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(QLDuAn.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTenKH.setEditable(false);
        txtTiendo.setText("Chưa bắt đầu");
        txtTiendo.setEditable(false);
        setColumn();
    }
    public void setColumn()
    {
        tabDuanCHT.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabDuanCHT.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabDuanCHT.getColumnModel().getColumn(2).setPreferredWidth(20);
        tabDuanCHT.getColumnModel().getColumn(3).setPreferredWidth(50);
        tabDuanCHT.getColumnModel().getColumn(4).setPreferredWidth(150);
        tabDuanCHT.getColumnModel().getColumn(5).setPreferredWidth(50);
        tabDuanCHT.getColumnModel().getColumn(6).setPreferredWidth(70);
        tabDuanCHT.getColumnModel().getColumn(7).setPreferredWidth(50);
        tabDuanCHT.getColumnModel().getColumn(8).setPreferredWidth(50);
        tabDuanCHT.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    private void tabDuanCHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDuanCHTMouseClicked
        // TODO add your handling code here:
        int i = tabDuanCHT.getSelectedRow();
        TableModel model = tabDuanCHT.getModel();
        txtID.setText(model.getValueAt(i, 0).toString());
        txtTenDA.setText(model.getValueAt(i, 1).toString());
        txtIDKH.setText(model.getValueAt(i, 2).toString());
        txtTenKH.setText(model.getValueAt(i, 3).toString());
        txtDiadiem.setText(model.getValueAt(i, 4).toString());
        txtDatcoc.setText(model.getValueAt(i, 7).toString());
        txtTiendo.setText(model.getValueAt(i, 8).toString());
        String tiendo = model.getValueAt(i, 8).toString();
        if(tiendo.equals("Đang tiến hành") || tiendo.equals("Hoàn thành")){
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        }else{
            btnThem.setEnabled(true);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }
        txtID.setEditable(false);
        txtIDKH.setEditable(false);
    }//GEN-LAST:event_tabDuanCHTMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        if(txtID.getText().equals("") || txtIDKH.getText().equals("") || txtTenDA.getText().equals("") || txtTenKH.getText().equals("") 
            || txtDiadiem.getText().equals("") || txtDatcoc.getText().equals("") || cldNgaykiHD.getDateFormatString().equals("") || cldTimeDK.getDateFormatString().equals("")){
            JOptionPane.showMessageDialog(this, "vui lòng nhập thông tin đầy đủ !");
        }
        else{
            String x = txtDatcoc.getText();
            Pattern pattern = Pattern.compile("\\d*");
            Matcher matcher = pattern.matcher(x);
            if (!matcher.matches()) {
                txtDatcoc.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Hãy nhập vào 1 số !");
            }
            else{
                txtDatcoc.setBackground(Color.white);
                String IDDA = txtID.getText();
                String IDKH = txtIDKH.getText();
                String tenda = txtTenDA.getText();
                String tiendo = txtTiendo.getText();
                int datcoc = Integer.parseInt(txtDatcoc.getText());
                String diaiem = txtDiadiem.getText();
                
                SimpleDateFormat formatNHTDK = new SimpleDateFormat("dd/MM/yyyy");
                String nhtdk = formatNHTDK.format(cldTimeDK.getDate());
                SimpleDateFormat formatNKHD = new SimpleDateFormat("dd/MM/yyyy");         
                String nkhd = formatNKHD.format(cldNgaykiHD.getDate()) ;
                rs = acc.Query("select IDDA from DuAn where IDDA = '"+IDDA+"'");
                try {
                    if(rs.next()){
                        JOptionPane.showMessageDialog(this, "Mã dự án đã tồn tại !!!");      
                    }else{
                        acc.Update("insert into DuAn values ('"+IDDA+"',N'"+tenda+"','"+IDKH+"','"+nkhd+"',N'"+diaiem+"','"+nhtdk+"','"+datcoc+"',N'"+tiendo+"')");
                        JOptionPane.showMessageDialog(this, "Thêm thành công !");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(QLDuAn.class.getName()).log(Level.SEVERE, null, ex);
                }
                LoadData();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        if(txtTenDA.getText().equals("") || txtTenKH.getText().equals("") 
            || txtDiadiem.getText().equals("") || txtDatcoc.getText().equals("") || cldNgaykiHD.getDateFormatString().equals("") || cldTimeDK.getDateFormatString().equals("")){
            JOptionPane.showMessageDialog(this, "vui lòng nhập thông tin đầy đủ !");
        }
        else{
            String x = txtDatcoc.getText();
            Pattern pattern = Pattern.compile("\\d*");
            Matcher matcher = pattern.matcher(x);
            if (!matcher.matches()) {
                txtDatcoc.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Hãy nhập vào 1 số !");
            }else{
                String IDDA = txtID.getText();
                String IDKH = txtIDKH.getText();
                String tenda = txtTenDA.getText();
                String tiendo = txtTiendo.getText();
                int datcoc = Integer.parseInt(txtDatcoc.getText());
                String diaiem = txtDiadiem.getText();
                SimpleDateFormat formatNHTDK = new SimpleDateFormat("dd/MM/yyyy");
                String nhtdk = formatNHTDK.format(cldTimeDK.getDate());
                SimpleDateFormat formatNKHD = new SimpleDateFormat("dd/MM/yyyy");         
                String nkhd = formatNKHD.format(cldNgaykiHD.getDate()) ;
                acc.Update("update DuAn set TenDA = N'"+tenda+"',IDKH = '"+IDKH+"',NgayKiHopDong = '"+nkhd+"',DiaDiem = N'"+diaiem+"',ThoiGianDuKienHoanThanh = '"+nhtdk+"',DatCoc = '"+datcoc+"',TienDoDA = N'"+tiendo+"' where IDDA = '"+IDDA+"'");
                LoadData();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        int remove = tabDuanCHT.getSelectedRow();
        if(remove == -1){
            JOptionPane.showMessageDialog(null, "vui lòng chọn 1 dòng để xóa !!!");
        }else{
            String IDDA = txtID.getText();
            acc.Update("DELETE from DuAn where IDDA = '"+IDDA+"' ");
        }
        LoadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        long millis = System.currentTimeMillis();   
        Date date = new Date(millis); 
        txtID.setText("");txtIDKH.setText("");txtTenDA.setText("");
        txtTenKH.setText("");txtTiendo.setText("Chưa bắt đầu");
        txtDiadiem.setText("");txtDatcoc.setText("");
        cldNgaykiHD.setDate(date);cldTimeDK.setDate(date);
        txtID.setEditable(true);txtIDKH.setEditable(true);
        btnThem.setEnabled(true);btnSua.setEnabled(true);btnXoa.setEnabled(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtIDKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKHKeyReleased
        // TODO add your handling code here:
        String IDKH = txtIDKH.getText();
        DBAccess acc = new DBAccess();
        try{
            if(txtIDKH.getText().equals("")){
                LoadData();
            }
            else{
                rs = acc.Query("select * from DuAn,QLThongTinKH where QLThongTinKH.IDKH like '"+IDKH+"' and DuAn.IDKH = QLThongTinKH.IDKH ");
                while(rs.next())
                {
                    txtTenKH.setText(rs.getString("HoTen"));
                }
            }
         } catch (SQLException ex) {
            Logger.getLogger(QLDuAn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIDKHKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QLDuAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private com.toedter.calendar.JDateChooser cldNgaykiHD;
    private com.toedter.calendar.JDateChooser cldTimeDK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabDuanCHT;
    private javax.swing.JTextField txtDatcoc;
    private javax.swing.JTextPane txtDiadiem;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDKH;
    private javax.swing.JTextField txtTenDA;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTiendo;
    // End of variables declaration//GEN-END:variables
}
