/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;

import DataBase.DBAccess;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public class QLPhanCongDA extends javax.swing.JFrame {
    public ResultSet rs = null ,rs1 = null;
    public String IDDA = null;
    public String IDNV = null;
    public String MaDA = null;
    private int i = 0;
    private int j = 0;

    /**
     * Creates new form QLPhanCongDA
     */
    public QLPhanCongDA() {
        initComponents();
        LoadDataDA();
        LoadDataNV();
        LoadDataPC();
        Data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabDuan = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabNhanvien = new javax.swing.JTable();
        btnPhancong = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabPhancong = new javax.swing.JTable();
        cldNgaynhanDA = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí phân công dự án");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 255));
        jLabel1.setText("Bảng phân công");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 386, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Phân công dự án");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 13, -1, -1));

        tabDuan.setBackground(new java.awt.Color(255, 255, 204));
        tabDuan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tabDuan.setForeground(new java.awt.Color(255, 0, 0));
        tabDuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dự án", "Tên dự án", "Khách hàng", "Ngày kí hợp đồng", "Địa điểm", "Đặt cọc", "Tiến độ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabDuan.setGridColor(new java.awt.Color(51, 51, 255));
        tabDuan.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tabDuan.setSelectionForeground(new java.awt.Color(255, 0, 0));
        tabDuan.getTableHeader().setReorderingAllowed(false);
        tabDuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDuanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabDuan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 93, 764, 181));

        btnThoat.setBackground(new java.awt.Color(255, 255, 102));
        btnThoat.setForeground(new java.awt.Color(0, 0, 153));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 631, -1, 30));

        tabNhanvien.setBackground(new java.awt.Color(255, 255, 204));
        tabNhanvien.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tabNhanvien.setForeground(new java.awt.Color(255, 0, 0));
        tabNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Giới tính"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabNhanvien.setGridColor(new java.awt.Color(51, 51, 255));
        tabNhanvien.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tabNhanvien.setSelectionForeground(new java.awt.Color(255, 0, 0));
        tabNhanvien.getTableHeader().setReorderingAllowed(false);
        tabNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabNhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabNhanvien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 93, 434, 181));

        btnPhancong.setBackground(new java.awt.Color(255, 255, 204));
        btnPhancong.setForeground(new java.awt.Color(255, 51, 51));
        btnPhancong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Favorites_16x16.png"))); // NOI18N
        btnPhancong.setText("Phân công");
        btnPhancong.setBorder(new javax.swing.border.MatteBorder(null));
        btnPhancong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhancongActionPerformed(evt);
            }
        });
        getContentPane().add(btnPhancong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 300, 100, 48));

        btnXoa.setBackground(new java.awt.Color(255, 255, 204));
        btnXoa.setForeground(new java.awt.Color(204, 0, 51));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1137, 627, 91, 34));

        tabPhancong.setBackground(new java.awt.Color(255, 255, 204));
        tabPhancong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tabPhancong.setForeground(new java.awt.Color(255, 0, 0));
        tabPhancong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dự án", "Tên dự án", "Khách hàng", "Tên nhân viên", "Ngày nhận DA", "Tiến độ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabPhancong.getTableHeader().setReorderingAllowed(false);
        tabPhancong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPhancongMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabPhancong);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 432, 1216, 182));

        cldNgaynhanDA.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(cldNgaynhanDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 309, 153, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Ngày nhận dự án");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 309, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QLPHANCONG.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 677));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void LoadDataDA () 
    {
        DBAccess acc = new DBAccess();
        try
        {
            rs = acc.Query("select * from DuAn,QLThongTinKH where TienDoDA = N'Chưa bắt đầu' and QLThongTinKH.IDKH = DuAn.IDKH");
            String [] arr = {"Mã dự án","Tên dự án","Tên khách hàng","Địa điểm","Ngày kí hợp đồng","Đặt cọc","Tiến độ"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDDA"));
                vec.add(rs.getString("TenDA"));
                vec.add(rs.getString("HoTenKH"));
                vec.add(rs.getString("DiaDiem"));
                vec.add(rs.getString("NgayKiHopDong"));
                vec.add(rs.getInt("DatCoc"));
                vec.add(rs.getString("TienDoDA"));
                IDDA = rs.getString("IDDA");
                model.addRow(vec);
            }
            tabDuan.setModel(model);
            rs.close();     
        } catch (SQLException ex) {
            Logger.getLogger(QLPhanCongDA.class.getName()).log(Level.SEVERE, null, ex);
        }
        btnPhancong.setEnabled(false);
        setColumn();
    }
    public void LoadDataNV() 
    {
        DBAccess acc = new DBAccess();
        try
        {
            rs = acc.Query("select * from QLNhanVien where IDNV in (select IDNV from QLNhanVien except (select IDNV from QLPhanCong where TienDo = N'Đang tiến hành') ) and IDCV = 'CV03'");
            String [] arr = {"Mã nhân viên","Tên nhân viên","Giới tính"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDNV"));
                vec.add(rs.getString("HoTen"));
                vec.add(rs.getString("GioiTinh"));
                model.addRow(vec);
            }
            tabNhanvien.setModel(model);
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(QLPhanCongDA.class.getName()).log(Level.SEVERE, null, ex);
        }
        setColumn();
    }
    public void LoadDataPC()
    {
        DBAccess acc = new DBAccess();
        try
        {
            rs = acc.Query("select QLPhanCong.IDDA,TenDA,HoTenKH,HoTen,NgayNhan,TienDo from QLPhanCong,DuAn,QLNhanVien,QLThongTinKH \n" +
                           "where QLPhanCong.IDDA = DuAn.IDDA and QLPhanCong.IDNV = QLNhanVien.IDNV and DuAn.IDKH = QLThongTinKH.IDKH");
            String [] arr = {"Mã dự án","Tên dự án","Tên khách hàng","Nhân viên phụ trách","Ngày nhận dự án","Tiến độ"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDDA"));
                vec.add(rs.getString("TenDA"));
                vec.add(rs.getString("HoTenKH"));
                vec.add(rs.getString("HoTen"));
                vec.add(rs.getString("NgayNhan"));
                vec.add(rs.getString("TienDo"));
                model.addRow(vec);
            }
            tabPhancong.setModel(model);
            rs.close();     
        } catch (SQLException ex) {
            Logger.getLogger(QLPhanCongDA.class.getName()).log(Level.SEVERE, null, ex);
        }
        setColumn();
    }
    private void Data()
    {
        long millis = System.currentTimeMillis();   
        Date date = new Date(millis);   
        cldNgaynhanDA.setDate(date);
        i = tabDuan.getSelectedRow();
        j = tabNhanvien.getSelectedRow();
        if(i != -1 && j != -1){
            btnPhancong.setEnabled(true);
        }else{
            btnPhancong.setEnabled(false);
        }
    }
    public void setColumn()
    {
        tabDuan.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabDuan.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabDuan.getColumnModel().getColumn(2).setPreferredWidth(50);
        tabDuan.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabDuan.getColumnModel().getColumn(4).setPreferredWidth(30);
        tabDuan.getColumnModel().getColumn(5).setPreferredWidth(30);
        tabDuan.getColumnModel().getColumn(6).setPreferredWidth(40);
        tabDuan.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        tabNhanvien.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabNhanvien.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabNhanvien.getColumnModel().getColumn(2).setPreferredWidth(20);
        tabNhanvien.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        tabPhancong.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabPhancong.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabPhancong.getColumnModel().getColumn(2).setPreferredWidth(50);
        tabPhancong.getColumnModel().getColumn(3).setPreferredWidth(50);
        tabPhancong.getColumnModel().getColumn(4).setPreferredWidth(30);
        tabPhancong.getColumnModel().getColumn(5).setPreferredWidth(30);
        tabPhancong.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    private void tabDuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDuanMouseClicked
        // TODO add your handling code here:
        i = tabDuan.getSelectedRow();
        TableModel model = tabDuan.getModel();
        IDDA = model.getValueAt(i, 0).toString();  
        Data();
    }//GEN-LAST:event_tabDuanMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tabNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabNhanvienMouseClicked
        // TODO add your handling code here:
        j = tabNhanvien.getSelectedRow();
        TableModel model = tabNhanvien.getModel();
        IDNV = model.getValueAt(j, 0).toString();  
        Data();
    }//GEN-LAST:event_tabNhanvienMouseClicked

    private void tabPhancongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPhancongMouseClicked
        // TODO add your handling code here:
        int a = tabPhancong.getSelectedRow();
        TableModel model = tabPhancong.getModel();
        MaDA = model.getValueAt(a, 0).toString();
        String TienDo = model.getValueAt(a, 5).toString();
        if(TienDo.equals("Hoàn thành")){
            btnXoa.setEnabled(false);
        }else{
            btnXoa.setEnabled(true);
        }  
        cldNgaynhanDA.setDateFormatString(model.getValueAt(a, 4).toString());
    }//GEN-LAST:event_tabPhancongMouseClicked

    private void btnPhancongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhancongActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String ngaynhanDA = format.format(cldNgaynhanDA.getDate());
        String tiendo = "Đang tiến hành";
        acc.Update("insert into QLPhanCong values('"+IDDA+"','"+IDNV+"','"+ngaynhanDA+"',N'"+tiendo+"')");
        acc.Update("update DuAn set TienDoDA = N'"+tiendo+"' where IDDA = '"+IDDA+"'");
        LoadDataDA();
        LoadDataNV();
        LoadDataPC();
    }//GEN-LAST:event_btnPhancongActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String tiendo = "Chưa bắt đầu";
        DBAccess acc = new DBAccess();
        int a = tabPhancong.getSelectedRow();
        if(a == -1){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa !!");
        }else{
            acc.Update("delete from QLPhanCong where IDDA = '"+MaDA+"'");
            acc.Update("update DuAn set TienDoDA = N'"+tiendo+"' where IDDA = '"+MaDA+"'");
            LoadDataDA();
            LoadDataNV();
            LoadDataPC();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPhanCongDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPhanCongDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPhanCongDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPhanCongDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QLPhanCongDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhancong;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private com.toedter.calendar.JDateChooser cldNgaynhanDA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabDuan;
    private javax.swing.JTable tabNhanvien;
    private javax.swing.JTable tabPhancong;
    // End of variables declaration//GEN-END:variables
}
