/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;

import DataBase.DBAccess;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.ButtonGroup;
/**
 *
 * @author Administrator
 */
public class QLThongTinCongNhan extends javax.swing.JFrame {
    public static ResultSet rs = null ;

    /**
     * Creates new form QLThueNhanCong
     */
    public QLThongTinCongNhan() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(rdbNu);
        group.add(rdbNam);
        LoadData();
        rdbNam.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbbChucvu = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabCongnhan = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDiachi = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí thông tin công nhân");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("DANH SÁCH CÔNG NHÂN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 13, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete_16x16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit_16x16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add_16x16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Mã công nhân");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Họ tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Số điện thoại");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Địa chỉ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
        getContentPane().add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 114, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Chức vụ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 25));

        cbbChucvu.setBackground(new java.awt.Color(153, 255, 153));
        cbbChucvu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbChucvu.setForeground(new java.awt.Color(102, 102, 0));
        cbbChucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công nhân thời vụ", "Giám sát công trường", "Công nhân chính thức" }));
        cbbChucvu.setToolTipText("");
        getContentPane().add(cbbChucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 252, 190, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 74, 139, -1));
        getContentPane().add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 211, 139, -1));

        tabCongnhan.setBackground(new java.awt.Color(255, 255, 51));
        tabCongnhan.setForeground(new java.awt.Color(0, 0, 204));
        tabCongnhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã công nhân", "Họ tên", "Giới tính", "Số điện thoại", "Chức vụ", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabCongnhan.getTableHeader().setReorderingAllowed(false);
        tabCongnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCongnhanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabCongnhan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 780, 270));

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Exit");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 390, 90, 30));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh_16x16.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Giới tính");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        rdbNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbNam.setForeground(new java.awt.Color(255, 153, 255));
        rdbNam.setText("Nam");
        getContentPane().add(rdbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 160, -1, -1));

        rdbNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbNu.setForeground(new java.awt.Color(255, 153, 255));
        rdbNu.setText("Nữ");
        getContentPane().add(rdbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 160, -1, -1));

        jScrollPane3.setViewportView(txtDiachi);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nenQL.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1143, 437));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void LoadData () 
    {
        DBAccess acc = new DBAccess();
        try { 
            rs = acc.Query("select *  from QLCongNhan,ChucVuCongNhan where QLCongNhan.IDCVCN = ChucVuCongNhan.IDCVCN");
            String [] arr = {"Mã công nhân","Họ tên","Giới tính","Số điện thoại","Chức vụ","Địa chỉ"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            while(rs.next())
            {
                Vector vec = new Vector();
                vec.add(rs.getString("IDCN"));
                vec.add(rs.getString("HoTen"));
                vec.add(rs.getString("GioiTinh"));
                vec.add(rs.getString("SDT"));
                vec.add(rs.getString("ChucVu"));
                vec.add(rs.getString("DiaChi"));
                                  
                model.addRow(vec);
            }
            tabCongnhan.setModel(model);
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(QLThongTinCongNhan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        int remove = tabCongnhan.getSelectedRow();
        if(remove == -1){
            JOptionPane.showMessageDialog(null, "vui lòng chọn 1 dòng để xóa !!!");
        }else{
            String IDCN = txtID.getText();
            acc.Update("DELETE from QLCongNhan where IDCN = '"+IDCN+"' ");
        }
        LoadData();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        if(txtSDT.getText().equals("") || txtHoten.getText().equals("") || txtDiachi.getText().equals("")){
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin");
        }else{
            ButtonGroup group = new ButtonGroup();
            group.add(rdbNu);
            group.add(rdbNam);
            String GioiTinh;
            if(rdbNu.isSelected() == true){
                GioiTinh = rdbNu.getText();
            }else{
                GioiTinh = rdbNam.getText();
            }
            String IDCN = txtID.getText();
            String HOTEN = txtHoten.getText();
            String SDT = txtSDT.getText();
            String IDCV =  (String) cbbChucvu.getSelectedItem();
            String Diachi  = txtDiachi.getText();
            try {
                acc.UpdateCN(IDCN, HOTEN, GioiTinh, SDT, IDCV, Diachi);
            } catch (SQLException ex) {
                Logger.getLogger(QLThongTinNhanvien.class.getName()).log(Level.SEVERE, null, ex);
            }
            LoadData();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        DBAccess acc = new DBAccess();
        if(txtID.getText().equals("") || txtSDT.getText().equals("") || txtHoten.getText().equals("") || txtDiachi.getText().equals("")){
            JOptionPane.showMessageDialog(this, "vui lòng điền đầy đủ thông tin");
        }else{
            ButtonGroup group = new ButtonGroup();
            group.add(rdbNu);
            group.add(rdbNam);
            String IDCN = txtID.getText();
            String Hoten = txtHoten.getText();
            String GioiTinh;
            if(rdbNu.isSelected() == true){
                GioiTinh = rdbNu.getText();
            }else{
                GioiTinh = rdbNam.getText();
            }
            String SDT = txtSDT.getText();
            String IDCV =  (String) cbbChucvu.getSelectedItem();
            String Diachi = txtDiachi.getText();
            rs = acc.Query("select IDNV from QLNhanVien where IDNV = '"+IDCN+"'");
            try {
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại !!!");
                }else{
                    acc.InsertCN(IDCN, Hoten, GioiTinh, SDT, IDCV, Diachi);
                }
            } catch (SQLException ex) {
                Logger.getLogger(QLThongTinCongNhan.class.getName()).log(Level.SEVERE, null, ex);
            }
            LoadData();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tabCongnhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCongnhanMouseClicked
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(rdbNu);
        group.add(rdbNam);
        int i = tabCongnhan.getSelectedRow();
        TableModel model = tabCongnhan.getModel();
        cbbChucvu.setSelectedItem(model.getValueAt(i, 4).toString());
        txtID.setText(model.getValueAt(i, 0).toString());
        txtHoten.setText(model.getValueAt(i, 1).toString());
        txtSDT.setText(model.getValueAt(i, 3).toString());
        txtDiachi.setText(model.getValueAt(i, 5).toString());
        if(model.getValueAt(i, 2).toString().equals("Nữ")){
            rdbNu.setSelected(true);
            rdbNam.setSelected(false);
        }else{
            rdbNam.setSelected(true);
            rdbNu.setSelected(false);
        }
        txtID.setEditable(false);
    }//GEN-LAST:event_tabCongnhanMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        cbbChucvu.setSelectedItem(0);
        txtID.setText("");
        txtHoten.setText("");
        txtSDT.setText("");
        txtDiachi.setText("");
        txtID.setEnabled(true);
        rdbNam.setSelected(true);
        txtID.setEditable(true);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLThongTinCongNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLThongTinCongNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLThongTinCongNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLThongTinCongNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLThongTinCongNhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbChucvu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JTable tabCongnhan;
    private javax.swing.JTextPane txtDiachi;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
