/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLi;

import Admin.Login;

/**
 *
 * @author Administrator
 */
public class QuanLi extends javax.swing.JFrame {

    /**
     * Creates new form QuanLi
     */
    public QuanLi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQLDA = new javax.swing.JButton();
        btnQLTTKH = new javax.swing.JButton();
        btnQLPC = new javax.swing.JButton();
        btnQLTTCN = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnQLTTNV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLDA.setBackground(new java.awt.Color(255, 255, 204));
        btnQLDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Documents-icon.png"))); // NOI18N
        btnQLDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDAActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 60, 110, 109));

        btnQLTTKH.setBackground(new java.awt.Color(255, 255, 204));
        btnQLTTKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhanvien.png"))); // NOI18N
        btnQLTTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTTKHActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLTTKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 249, 110, 119));

        btnQLPC.setBackground(new java.awt.Color(255, 255, 204));
        btnQLPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Actions-clipboard-icon.png"))); // NOI18N
        btnQLPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLPCActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 60, 109, 109));

        btnQLTTCN.setBackground(new java.awt.Color(255, 255, 204));
        btnQLTTCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Occupations-Firefighter-Female-Light-icon.png"))); // NOI18N
        btnQLTTCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTTCNActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLTTCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 109, 109));

        btnThoat.setBackground(new java.awt.Color(255, 255, 0));
        btnThoat.setForeground(new java.awt.Color(0, 0, 204));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        btnQLTTNV.setBackground(new java.awt.Color(255, 255, 204));
        btnQLTTNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Office-Client-Female-Light-icon.png"))); // NOI18N
        btnQLTTNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTTNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnQLTTNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 249, 109, 119));

        jLabel1.setText("Quản lí phân công dự án");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 187, -1, -1));

        jLabel2.setText("Quản lí kí dự án");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 187, -1, -1));

        jLabel3.setText("Quản lí thông tin công nhân");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 187, -1, -1));

        jLabel4.setText("Quản lí thông tin khách hàng");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 381, -1, -1));

        jLabel5.setText("Quản lí thông tin nhân viên");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 381, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hinh-nen-trang-ban-do-the-gioi_104325245.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 578, 425));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnQLDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDAActionPerformed
        // TODO add your handling code here:
        QLDuAn da = new QLDuAn();
        da.setVisible(true);
    }//GEN-LAST:event_btnQLDAActionPerformed

    private void btnQLPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPCActionPerformed
        // TODO add your handling code here:
        QLPhanCongDA qlpc = new QLPhanCongDA();
        qlpc.setVisible(true);
    }//GEN-LAST:event_btnQLPCActionPerformed

    private void btnQLTTCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTTCNActionPerformed
        // TODO add your handling code here:
        QLThongTinCongNhan qlcn = new QLThongTinCongNhan();
        qlcn.setVisible(true);
    }//GEN-LAST:event_btnQLTTCNActionPerformed

    private void btnQLTTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTTKHActionPerformed
        // TODO add your handling code here:
        QLThongTinKhachHang qlkh = new QLThongTinKhachHang();
        qlkh.setVisible(true);
    }//GEN-LAST:event_btnQLTTKHActionPerformed

    private void btnQLTTNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTTNVActionPerformed
        // TODO add your handling code here:
        QLThongTinNhanvien qlnv = new QLThongTinNhanvien();
        qlnv.setVisible(true);
    }//GEN-LAST:event_btnQLTTNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QuanLi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLDA;
    private javax.swing.JButton btnQLPC;
    private javax.swing.JButton btnQLTTCN;
    private javax.swing.JButton btnQLTTKH;
    private javax.swing.JButton btnQLTTNV;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
