/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TaiKhoan;

import java.util.Random;
import javax.swing.JOptionPane;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author Administrator
 */
public class Emailvacode extends javax.swing.JFrame {

    private int randomCode;

    public Emailvacode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaxacnhan = new javax.swing.JTextField();
        txtEmailsend = new javax.swing.JTextField();
        btnGuima = new javax.swing.JButton();
        btnKiemtra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Email xác nhận");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Mã xác nhận");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        getContentPane().add(txtMaxacnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 208, -1));
        getContentPane().add(txtEmailsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, -1));

        btnGuima.setBackground(new java.awt.Color(255, 255, 204));
        btnGuima.setForeground(new java.awt.Color(0, 0, 153));
        btnGuima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Send_16x16.png"))); // NOI18N
        btnGuima.setText("Gửi mã");
        btnGuima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuimaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuima, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        btnKiemtra.setBackground(new java.awt.Color(255, 255, 204));
        btnKiemtra.setForeground(new java.awt.Color(0, 0, 153));
        btnKiemtra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Check_16x16.png"))); // NOI18N
        btnKiemtra.setText("Kiểm tra");
        btnKiemtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemtraActionPerformed(evt);
            }
        });
        getContentPane().add(btnKiemtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Nhập Email để được gửi mã xác nhận");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 31));

        btnThoat.setBackground(new java.awt.Color(255, 255, 204));
        btnThoat.setForeground(new java.awt.Color(0, 0, 153));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Undo_16x16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 91, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 256));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        
    private void btnGuimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuimaActionPerformed
        // TODO add your handling code here:
        try{
            Random rand = new Random();
            randomCode=rand.nextInt(999999);
            String host = "smtp.gmail.com";
            String user ="daylaemaildein555@gmail.com";
            String pass="spmhbmhqmvaqdgyq";
            String to = txtEmailsend.getText();
            String subject="Reseting Code";
            String message ="Your reset code is "+randomCode;
            boolean sessionDebug = false;
            Properties pros = System.getProperties();

            pros.put("mail.smtp.starttls.enable", "true");
            pros.put("mail.smtp.host", "host");
            pros.put("mail.smtp.port","25");
            pros.put("mail.smtp.auth","true");
            pros.put("mail.smtp.EnableSSL.enable","true");

            pros.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");   
            pros.setProperty("mail.smtp.socketFactory.fallback", "false");   
            pros.setProperty("mail.smtp.port", "465");   
            pros.setProperty("mail.smtp.socketFactory.port", "465"); 

            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            
            Authenticator authenticator = new Authenticator () {
                @Override
                public PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication("user","pass"); 
                }
            };  
           
            Session mailSession = Session.getDefaultInstance( pros , authenticator);
           
            mailSession.setDebug(sessionDebug);
            Message msg = new MimeMessage(mailSession);
            msg.setFrom(new InternetAddress(user));
            InternetAddress [] address = {new InternetAddress(to)};
            msg.setRecipients(Message.RecipientType.TO, address);
            msg.setSubject(subject);
            msg.setText(message);
            Transport transport = mailSession.getTransport("smtp");
            transport.connect(host, user, pass);
            transport.sendMessage(msg, msg.getAllRecipients());
            transport.close();
            JOptionPane.showMessageDialog(null, "Mã xác nhận đã gửi đến email của bạn"
                    + "\nVui lòng kiểm tra !!");
        }catch(Exception ex){
        JOptionPane.showMessageDialog(rootPane, ex);
        }       
    }//GEN-LAST:event_btnGuimaActionPerformed

    private void btnKiemtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemtraActionPerformed
        String x = txtMaxacnhan.getText();
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(x);
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(null, "Mã xác nhận phải là 1 số !");
        } else {
            if(Integer.valueOf(txtMaxacnhan.getText())==randomCode)
            {
                JOptionPane.showMessageDialog(null, "Mã xác nhận chính xác !");
                Quenpass frm = new Quenpass();
                frm.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Mã xác nhận không chính xác !");
            }    
        }
    }//GEN-LAST:event_btnKiemtraActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emailvacode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emailvacode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emailvacode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emailvacode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Emailvacode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuima;
    private javax.swing.JButton btnKiemtra;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEmailsend;
    private javax.swing.JTextField txtMaxacnhan;
    // End of variables declaration//GEN-END:variables
}
